#!/bin/bash
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
# hdrAnySQL_1.sh - Any .sql to .sh shell source.
# 5/17/24.	wmk.
#
# Usage. bash   ListCountTerrsbyDB.sh
#		
# Modification History.
# ---------------------
# 5/17/24.	wmk.	(automated) Modification History sorted.
# 5/17/24.	wmk.	SetToday code improved. 
# 4/23/24.	wmk.	SetToday executed from */sysprocs. 
# 3/16/24.	wmk.	-v added to SetToday; P1 preserved across SetToday call. 
# 11/19/23.	wmk.	comments tidied; compatible with Version 3.0.6. 
# 11/12/23.	wmk.	*folderbase, *pathbase, *codebase, *system_log environment 
# 11/12/23.	 var definitions removed. 
# 10/14/23.	wmk.	*gitpath replaced with *codebase. 
# 10/5/23.	wmk.	ver2.0 paths checked; ~/GitHub changed to *git_path. 
# 9/3/23.	wmk.	(automated) ver2.0 path fixes. 
# 12/12/22.	wmk.	SetTody.sh path corrected. 
# 12/11/22.	wmk.	run SetToday.sh to export TODAY env var. 
# 10/4/22.	wmk.	(automated) fix *pathbase for CB system. 
# 4/23/22.	wmk.	modified for FL/SARA/86777. 
# 4/22/22.	wmk.	HOME changed to USER in host check. 
# 4/8/22.	wmk.	HOME changed to USER in host test. 
# 12/3/21.	wmk.	'procbodyhere' replaces proc body here for awk reversal. 
# 11/9/21.	wmk.	add echo when initiated from make; add $ TODAY definition. 
# 9/6/21.	wmk.	jumpto function and references removed. 
# 6/17/21.	wmk.	multihost support. 
# 4/6/21.	wmk.	original shell (template) 
#
# P1 = (assumed) territory ID
#
P1=$1
TID=$P1
TN="Terr"
#	Environment vars:
if [ -z "$TODAY" ];then
 lclp1=$P1
 . ~/sysprocs/SetToday.sh -v
 P1=$ldlp1
fi
NAME_BASE="Terr"
SC_DB="_SC.db"
RU_DB="_RU.db"
SC_SUFFX="_SCBridge"
RU_SUFFX="_RUBridge"

#procbodyhere

printf "%s\n" "-- *ListCountTerrsbyDB.psq/sql - List territories using special database."  > SQLTemp.sql
printf "%s\n" "-- 2023-09-11   wmk.   (automated) ver2.0 SQL fixes."  >> SQLTemp.sql
printf "%s\n" "-- *	12/20/22.	wmk."  >> SQLTemp.sql
printf "%s\n" ".open '$pathbase/RawData/RefUSA/RefUSA-Downloads/Special/WhitecapCir.db'"  >> SQLTemp.sql
printf "%s\n" ".output '$TEMP_PATH/DBTerrList.txt'"  >> SQLTemp.sql
printf "%s\n" "select TerrID from TerrList"  >> SQLTemp.sql
printf "%s\n" " where length(trim(counts)) > 0 "  >> SQLTemp.sql
printf "%s\n" "  AND cast(Counts as integer) > 0"  >> SQLTemp.sql
printf "%s\n" "  AND TerrID NOT NULL"  >> SQLTemp.sql
printf "%s\n" "  order by TerrID;"  >> SQLTemp.sql
printf "%s\n" ".quit"  >> SQLTemp.sql
printf "%s\n" "-- * end ListCountTerrsbyDB.psq/sql"  >> SQLTemp.sql
# hdrAnySQL_2.sh - postscript for shells generated by AnySQLtoSH.
# 2023-12-31.	wmk.	(automated) Version 3.0.6 paths eliminated (HPPavilion).
# 2023-09-03   wmk.   (automated) ver2.0 path fixes.
# 2023-09-01   wmk.   (automated) ver2.0 path fixes.
#endprocbody - changed from end proc body 12/3/21 for awk reversal.
# jumpto references removed 9/6/21.
sqlite3 < SQLTemp.sql
# postListTerrsByDB.sh
wc -l $TEMP_PATH/DBTerrList.txt | mawk -v specdb=WhitecapCir '{print specdb " used by " $1 " territories."}' >> $TEMP_PATH/DBSummary.txt
exit 0
# end postscript.
printf "%s\n" "  ListCountTerrsbyDB complete."
~/sysprocs/LOGMSG "  ListCountTerrsbyDB complete."
#end proc
  echo "cat DBTerrList.txt to see list of territories..."
