#!/bin/bash
echo " ** <filespec> out-of-date **";exit 1
# hdrAnySQL_1.sh - Any .sql to .sh shell source.
#	10/22/24.	wmk.
#
# Usage. bash   BldSpecStreetsDB.sh
#		
# Modification History.
# ---------------------
# 10/22/24.	wmk.	(automated) echo,s to printf,s throughout.
# 10/22/24.	wmk.	(automated) build level 4.0.9.
# 10/22/24.	wmk.	(automated) mods for build level 4.0.9.
# 5/17/24.	wmk.	(automated) Modification History sorted.
# 5/17/24.	wmk.	SetToday code improved. 
# 4/23/24.	wmk.	SetToday executed from */sysprocs. 
# 3/16/24.	wmk.	-v added to SetToday; P1 preserved across SetToday call. 
# 11/19/23.	wmk.	comments tidied; compatible with Version 3.0.6. 
# 11/12/23.	wmk.	*folderbase, *pathbase, *codebase, *system_log environment 
# 11/12/23.	 var definitions removed. 
# 10/14/23.	wmk.	*gitpath replaced with *codebase. 
# 10/5/23.	wmk.	ver2.0 paths checked; ~/GitHub changed to *git_path. 
# 9/3/23.	wmk.	(automated) ver2.0 path fixes. 
# 12/12/22.	wmk.	SetTody.sh path corrected. 
# 12/11/22.	wmk.	run SetToday.sh to export TODAY env var. 
# 10/4/22.	wmk.	(automated) fix *pathbase for CB system. 
# 4/23/22.	wmk.	modified for FL/SARA/86777. 
# 4/22/22.	wmk.	HOME changed to USER in host check. 
# 4/8/22.	wmk.	HOME changed to USER in host test. 
# 12/3/21.	wmk.	'procbodyhere' replaces proc body here for awk reversal. 
# 11/9/21.	wmk.	add printf "%s\n" when initiated from make; add $ TODAY definition. 
# 9/6/21.	wmk.	jumpto function and references removed. 
# 6/17/21.	wmk.	multihost support. 
# 4/6/21.	wmk.	original shell (template) 
#
# P1 = (assumed) territory ID
#
P1=$1
TID=$P1
TN="Terr"
#	Environment vars:
if [ -z "$TODAY" ];then
 lclp1=$P1
 . ~/sysprocs/SetToday.sh -v
 P1=$ldlp1
fi
NAME_BASE="Terr"
SC_DB="_SC.db"
RU_DB="_RU.db"
SC_SUFFX="_SCBridge"
RU_SUFFX="_RUBridge"

#procbodyhere

printf "%s\n" "-- * BldSpecStreetsDB.psq/sql - Build Streets table from /Special db."  > SQLTemp.sql
printf "%s\n" "-- *	12/26/24.	wmk."  >> SQLTemp.sql
printf "%s\n" "-- *"  >> SQLTemp.sql
printf "%s\n" "-- * Modification History."  >> SQLTemp.sql
printf "%s\n" "-- * ---------------------"  >> SQLTemp.sql
printf "%s\n" "-- * 12/26/24.	wmk.	(automated) build 4.0.12 updates."  >> SQLTemp.sql
printf "%s\n" "-- * 12/26/24.	wmk.	original."  >> SQLTemp.sql
printf "%s\n" "-- *"  >> SQLTemp.sql
printf "%s\n" "-- * Notes. < spec-db > will be changed to a /Special db name througout by "  >> SQLTemp.sql
printf "%s\n" "-- *  DoSedBldStreets.sh"  >> SQLTemp.sql
printf "%s\n" "-- * RefUSA-Downloads/Special/StreetNames.db . Streets is the target table."  >> SQLTemp.sql
printf "%s\n" "-- * The territory ID is now inserted along with the street names."  >> SQLTemp.sql
printf "%s\n" "-- * WARNING: this will only record the last street's territory ID, so"  >> SQLTemp.sql
printf "%s\n" "-- * will be inaccurate if a street is split across territories."  >> SQLTemp.sql
printf "%s\n" "-- *"  >> SQLTemp.sql
printf "%s\n" ".open '$pathbase/$rupath/Special/StreetNames.db"  >> SQLTemp.sql
printf "%s\n" "ATTACH '$pathbase/$rupath/Special/BayIndiesMHP.db'"  >> SQLTemp.sql
printf "%s\n" " AS db29;"  >> SQLTemp.sql
printf "%s\n" "INSERT or REPLACE INTO Streets("  >> SQLTemp.sql
printf "%s\n" " StreetName,"  >> SQLTemp.sql
printf "%s\n" " SourceDB,"  >> SQLTemp.sql
printf "%s\n" " TerrID"  >> SQLTemp.sql
printf "%s\n" ")"  >> SQLTemp.sql
printf "%s\n" "select distinct trim(substr(unitaddress,"  >> SQLTemp.sql
printf "%s\n" " instr(unitaddress,' '))) Streets, '*rupath/BayIndiesMHP.db',"  >> SQLTemp.sql
printf "%s\n" " CongTerrID"  >> SQLTemp.sql
printf "%s\n" " from db29.Spec_RUBridge;"  >> SQLTemp.sql
printf "%s\n" ""  >> SQLTemp.sql
printf "%s\n" ".quit"  >> SQLTemp.sql
printf "%s\n" "-- * END BldSpecStreetsDB.sql"  >> SQLTemp.sql
# hdrAnySQL_2.sh - postscript for shells generated by AnySQLtoSH.
# 2024-11-24.	wmk.	*sqlerror error handing added.
# 2024-10-22.	wmk.	-q option added to LOGMSG.
# 2024-10-22.	wmk.	(automated) mods for build level 4.0.9.
# 2023-12-31.	wmk.	(automated) Version 3.0.6 paths eliminated (HPPavilion).
# 2023-09-03   wmk.   (automated) ver2.0 path fixes.
# 2023-09-01   wmk.   (automated) ver2.0 path fixes.
#endprocbody - changed from end proc body 12/3/21 for awk reversal.
# jumpto references removed 9/6/21.
sqlite3 < SQLTemp.sql
# postBldStreets.sh - BuildStreetsDB.sh postprocessor.
#	12/26/24.	wmk
errcode=$?
if [ $errcode -ne 0 ];then
 echo "run GenNewStreetNamesDB.sh to create StreetNames.db Streets table."
fi
# end postBldStreets.sh
sqlerr=$?
printf "%s\n" "  BldSpecStreetsDB complete."
~/sysprocs/LOGMSG -q "  BldSpecStreetsDB complete."
if [ $sqlerr -ne 0 ];then
 echo " ** BldSpecStreetsDB SQL error - exiting with error **"
 exit 1
fi
#end proc
