#!/bin/bash
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
echo " ** <filespec> out-of-date **";exit 1
# hdrAnySQL.sh - Any .sql to .sh shell source.
# 4/23/24.	wmk.
#
# Usage. bash   WhichTerr.sh
#		
# Modification History.
# ---------------------
# 9/3/23.   wmk.    (automated) ver2.0 path fixes.
# 10/5/23.	wmk.	ver2.0 paths checked; ~/GitHub changed to *git_path.
# 10/14/23.	wmk.	*gitpath replaced with *codebase.
# 11/12/23.	wmk.	*folderbase, *pathbase, *codebase, *system_log environment
#			 var definitions removed.
# 11/19/23.	wmk.	comments tidied; compatible with Version 3.0.6.
# 3/16/24.	wmk.	-v added to SetToday; P1 preserved across SetToday call.
# 4/23/24.	wmk.	SetToday executed from */sysprocs.
# Legacy mods.
# 10/4/22.    wmk.   (automated) fix *pathbase for CB system.
# 12/11/22.	wmk.	run SetToday.sh to export TODAY env var.
# 12/12/22.	wmk.	SetTody.sh path corrected.
# Legacy mods.
# 4/23/22.	wmk.	modified for FL/SARA/86777.
# 4/22/22.	wmk.	HOME changed to USER in host check.
# Legacy mods.
# 4/6/21.	wmk.	original shell (template)
# 6/17/21.	wmk.	multihost support.
# 9/6/21.	wmk.	jumpto function and references removed.
# 11/9/21.	wmk.	add echo when initiated from make; add $ TODAY definition.
# 12/3/21.	wmk.	'procbodyhere' replaces proc body here for awk reversal.
# 4/8/22.	wmk.	HOME changed to USER in host test.	
P1=$1
TID=$P1
TN="Terr"
#	Environment vars:
if [ -z "$TODAY" ];then
 . ~/sysprocs/SetToday.sh -v
 P1=$TID
fi
NAME_BASE="Terr"
SC_DB="_SC.db"
RU_DB="_RU.db"
SC_SUFFX="_SCBridge"
RU_SUFFX="_RUBridge"

#procbodyhere

printf "%s\n" "-- * WhichTerr.psq/sql - SQL query to search Terrxxx_SCBridge table for address."  > SQLTemp.sql
printf "%s\n" "-- *	5/4/24.	wmk."  >> SQLTemp.sql
printf "%s\n" "-- *"  >> SQLTemp.sql
printf "%s\n" "-- * Notes. DoSedWhichTerr.sh edits < terrid > into search query."  >> SQLTemp.sql
printf "%s\n" "-- *"  >> SQLTemp.sql
printf "%s\n" ".open '$pathbase/$scpath/Terr137/Terr137_SC.db'"  >> SQLTemp.sql
printf "%s\n" ".separator \" \""  >> SQLTemp.sql
printf "%s\n" "SELECT 'Terr137_SC.db matching count = ', count(OwningParcel)"  >> SQLTemp.sql
printf "%s\n" "FROM Terr137_SCBridge"  >> SQLTemp.sql
printf "%s\n" "WHERE UnitAddress LIKE '%GREEN CIR%';"  >> SQLTemp.sql
printf "%s\n" ".quit"  >> SQLTemp.sql
printf "%s\n" "-- * END WhichTerr.sql"  >> SQLTemp.sql
# hdrAnySQL_2.sh - postscript for shells generated by AnySQLtoSH.
# 2023-12-31.	wmk.	(automated) Version 3.0.6 paths eliminated (HPPavilion).
# 2023-09-03   wmk.   (automated) ver2.0 path fixes.
# 2023-09-01   wmk.   (automated) ver2.0 path fixes.
#endprocbody - changed from end proc body 12/3/21 for awk reversal.
# jumpto references removed 9/6/21.
sqlite3 < SQLTemp.sql
printf "%s\n" "  WhichTerr complete."
~/sysprocs/LOGMSG "  WhichTerr complete."
#end proc
